config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :doses, only: %i[destroy]
  resources :cocktails do
    resources :doses, only: %i[index create new]
  end

  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %i[show edit update destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show; end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy

    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, except: %i[index]
  before_action :set_cocktail, except: %i[destroy]

  def index
    @doses = Dose.all.where(cocktail: @cocktail)
  end

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = @dose.cocktail
    @dose.destroy

    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
_form.html.erb

app/views/cocktails/edit.html.erb
edit.html.erb

app/views/cocktails/index.html.erb
<div class="row">
  <% @cocktails.each do |cktl| %>
    <div class="col-lg-2 col-md-3 col-sm-4 col-12">
      <%= link_to cocktail_path(cktl) do %>
        <div class="card my-4 bg-light shadow-sm bg-white rounded">
          <div class="card-img-top">
            <%= image_tag("https://source.unsplash.com/random?#{cktl.name}", style: "ojject-fit: cover; height: 150px;", class: "card-img-top") %>
          </div>
          <div class="card-body">
            <%= cktl.name %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
new.html.erb

app/views/cocktails/show.html.erb
<div id="individual">
  <div id="name">
    <h3><%= @cocktail.name %></h3>
  </div>
  <div id="info">
    <div class="cocktail-img m-2">
      <%= image_tag("https://source.unsplash.com/random?#{@cocktail.name}", class: "cover") %>
    </div>
    <div class="cocktail-ingredients w-100">
      <ul>
        <% @cocktail.ingredients.first(9).each do |ingredient| %>
          <% dose = @cocktail.doses.select { |dose| dose.ingredient == ingredient}.first %>
          <li class="d-flex justify-content-between"><%= dose.description %> of <%= ingredient.name %>
            <%= link_to dose_path(dose), method: :delete do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </li>
        <% end %>
        <% if @cocktail.doses.count >= 10 %>
          <%= link_to "...", cocktail_doses_path(@cocktail) %>
        <% end %>
      </ul>
      <div>
        <%= link_to "Add a Dose", new_cocktail_dose_path(@cocktail), class: "btn btn-success w-100 m-0" %>
      </div>
    </div>
  </div>
</div>

app/views/doses/_form.html.erb
_form.html.erb

app/views/doses/index.html.erb
<% @doses.each do |dose| %>
  <p><%= dose.description %> of <%= dose.ingredient.name %></p>
<% end %>

app/views/doses/new.html.erb
new.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="navbar bg-white mb-2">
      <%= link_to "Cocktails Master", cocktails_path %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <div id="scripts">
      <%= javascript_include_tag "application" %>
      <%= javascript_pack_tag "application" %>
    </div>
  </body>
</html>